import React, { useRef } from 'react';
import { useExport } from '../context/ExportContext';
import { shortcuts, applications, categories } from '../data';
import { Trash2, Download } from 'lucide-react';
// @ts-ignore
import html2pdf from 'html2pdf.js';

export const Export: React.FC = () => {
    const { selectedShortcuts, toggleShortcut, clearSelection } = useExport();
    const printRef = useRef<HTMLDivElement>(null);

    const selectedData = shortcuts.filter(s => selectedShortcuts.includes(s.id));

    // Group by App then Category
    const groupedByApp = applications.map(app => {
        const appShortcuts = selectedData.filter(s => s.appId === app.id);
        if (appShortcuts.length === 0) return null;

        const byCategory = categories.map(cat => ({
            ...cat,
            shortcuts: appShortcuts.filter(s => s.categoryId === cat.id)
        })).filter(g => g.shortcuts.length > 0);

        return {
            ...app,
            categories: byCategory
        };
    }).filter(Boolean);

    const handleExport = () => {
        if (!printRef.current) return;

        const element = printRef.current;
        const opt = {
            margin: 10,
            filename: 'shortcuts.pdf',
            image: { type: 'jpeg', quality: 0.98 } as any,
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' } as any
        };

        html2pdf().set(opt).from(element).save();
    };

    if (selectedShortcuts.length === 0) {
        return (
            <div className="text-center py-12">
                <h2 className="text-xl font-semibold text-gray-900">No shortcuts selected</h2>
                <p className="text-gray-500 mt-2">Go to an app page and select shortcuts to export.</p>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <h1 className="text-2xl font-bold text-gray-900">Export Configuration</h1>
                <div className="flex gap-3">
                    <button
                        onClick={clearSelection}
                        className="px-4 py-2 text-red-600 hover:bg-red-50 rounded-lg flex items-center gap-2"
                    >
                        <Trash2 size={18} />
                        Clear
                    </button>
                    <button
                        onClick={handleExport}
                        className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 flex items-center gap-2"
                    >
                        <Download size={18} />
                        Download PDF
                    </button>
                </div>
            </div>

            {/* Preview Area */}
            <div className="bg-gray-100 p-8 rounded-xl overflow-auto max-h-[800px] border border-gray-200">
                <div
                    ref={printRef}
                    className="bg-white shadow-lg mx-auto p-[20mm] min-h-[297mm] w-[210mm]"
                    style={{ transformOrigin: 'top center' }}
                >
                    <div className="text-center mb-8">
                        <h1 className="text-3xl font-bold text-gray-900">Shortcut Cheat Sheet</h1>
                        <p className="text-gray-500 mt-2">Generated by ShortcutMaster</p>
                    </div>

                    <div className="space-y-8">
                        {groupedByApp.map(app => (
                            <div key={app!.id} className="break-inside-avoid">
                                <div className="flex items-center gap-3 mb-4 border-b-2 border-gray-900 pb-2">
                                    {/* Icon placeholder if needed */}
                                    <h2 className="text-xl font-bold text-gray-900">{app!.name}</h2>
                                </div>

                                <div className="grid grid-cols-2 gap-x-8 gap-y-4">
                                    {app!.categories.map(cat => (
                                        <div key={cat.id} className="break-inside-avoid mb-4">
                                            <h3 className="font-semibold text-gray-700 mb-2 uppercase text-xs tracking-wider">{cat.name}</h3>
                                            <div className="space-y-2">
                                                {cat.shortcuts.map(s => (
                                                    <div key={s.id} className="flex justify-between items-start text-sm group">
                                                        <span className="text-gray-600 pr-2">{s.description}</span>
                                                        <div className="flex items-center gap-2 shrink-0">
                                                            <div className="flex gap-1">
                                                                {s.keys.map((k, i) => (
                                                                    <kbd key={i} className="font-mono font-bold text-gray-900 bg-gray-100 px-1 rounded border border-gray-300 text-xs">
                                                                        {k}
                                                                    </kbd>
                                                                ))}
                                                            </div>
                                                            <button
                                                                onClick={() => toggleShortcut(s.id)}
                                                                className="opacity-0 group-hover:opacity-100 text-red-400 hover:text-red-600 transition-opacity print:hidden"
                                                                title="Remove from export"
                                                            >
                                                                <Trash2 size={14} />
                                                            </button>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};
